// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjF9M212M9Fs2QsjCvfXujqY46BJUzZNA',
    appId: '1:114214795536:web:36e85df5e29c11f1a28d95',
    messagingSenderId: '114214795536',
    projectId: 'wind-alarm-agent-eb65f',
    authDomain: 'wind-alarm-agent-eb65f.firebaseapp.com',
    storageBucket: 'wind-alarm-agent-eb65f.firebasestorage.app',
    measurementId: 'G-73L123BVVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfWwobNaTEt76m3Ds7qVBRZx0pZC6fr7s',
    appId: '1:361158488010:android:495ee9f33ee648ae702933',
    messagingSenderId: '361158488010',
    projectId: 'wind-alarm-agent',
    storageBucket: 'wind-alarm-agent.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVFsr1G6JlKMJZKyLaJJEoMCAzYIiGGtM',
    appId: '1:114214795536:ios:63e8ecb84eb3d16ba28d95',
    messagingSenderId: '114214795536',
    projectId: 'wind-alarm-agent-eb65f',
    storageBucket: 'wind-alarm-agent-eb65f.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVFsr1G6JlKMJZKyLaJJEoMCAzYIiGGtM',
    appId: '1:114214795536:ios:63e8ecb84eb3d16ba28d95',
    messagingSenderId: '114214795536',
    projectId: 'wind-alarm-agent-eb65f',
    storageBucket: 'wind-alarm-agent-eb65f.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjF9M212M9Fs2QsjCvfXujqY46BJUzZNA',
    appId: '1:114214795536:web:a884b35a74832c34a28d95',
    messagingSenderId: '114214795536',
    projectId: 'wind-alarm-agent-eb65f',
    authDomain: 'wind-alarm-agent-eb65f.firebaseapp.com',
    storageBucket: 'wind-alarm-agent-eb65f.firebasestorage.app',
    measurementId: 'G-R61D37RZMH',
  );
}
