FROM public.ecr.aws/lambda/python:3.12
RUN pip install -r requirements.txt
# Copy src content to the root package
COPY src/wind_alarm/ ${LAMBDA_TASK_ROOT}/wind_alarm/
COPY app.py ${LAMBDA_TASK_ROOT}/

ENV PYTHONPATH=${LAMBDA_TASK_ROOT}

CMD ["wind_alarm.aws.lambda_handler.handler"]